version: '3'
services:
  astroplant-database:
    build: ../database
    environment:
      POSTGRES_DB: astroplant
      POSTGRES_USER: astroplant
      POSTGRES_PASSWORD: astroplant
    ports:
      - 5432:5432
  mqtt-broker:
    image: eclipse-mosquitto:1.6.8
    ports:
      - 1883:1883
    volumes:
      - ./mqtt-broker/config:/mosquitto/config:ro
  minio:
    image: minio/minio:RELEASE.2020-06-22T03-12-50Z
    ports:
      - 9000:9000
    environment:
      MINIO_BROWSER: "on"
      MINIO_ACCESS_KEY: admin
      MINIO_SECRET_KEY: miniopassword
    volumes:
      - ./data/minio:/data
    command: server /data
  create-minio-buckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
        sleep 5 &&
        mc config host add astroplant http://minio:9000 admin miniopassword &&
        mc mb astroplant/kit-media &&
        exit 0
      "
  astroplant-mqtt-connector:
    build:
        context: ..
        dockerfile: ./mqtt-connector/Dockerfile
    depends_on:
      - mqtt-broker
    environment:
      MQTT_HOST: mqtt-broker
      MQTT_USERNAME: server
      MQTT_PASSWORD: abcdef
      DATABASE_URL: postgresql+psycopg2://astroplant:astroplant@astroplant-database/astroplant
      LOG_LEVEL: DEBUG
  astroplant-api:
    build: ../../astroplant-api
    ports:
      - 8080:8080
    depends_on:
      - astroplant-database
      - mqtt-broker
    environment:
      DATABASE_URL: postgres://astroplant:astroplant@astroplant-database/astroplant
      MQTT_HOST: mqtt-broker
      MQTT_USERNAME: server
      MQTT_PASSWORD: abcdef
      AWS_S3_ENDPOINT: http://minio:9000
      AWS_ACCESS_KEY_ID: admin
      AWS_SECRET_ACCESS_KEY: miniopassword
  astroplant-frontend-web:
    build: ../../astroplant-frontend-web
    depends_on:
      - astroplant-api
    ports:
      - 3000:3000
    environment:
      REACT_APP_API_URL: http://localhost:8080
      REACT_APP_WS_URL: ws://localhost:8080
